# Schema for the configuration files of the Axelerant custom module.
axelerant_custom.settings:
  type: config_object
  label: 'Axelerant custom module settings'
  mapping:
    siteapikey:
      type: string
      label: 'API key of website'